config/routes.rb
Rails.application.routes.draw do
  resources :add_infos
  resources :users
  resources :posts
  resources :mobs
  
  root 'posts#index'
  

end

app/models/add_info.rb
class AddInfo < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    validates :name,:number, presence: true
    validates :name, length: { minimum: 2 }
    validates :number, length: { maximum: 15 }
    validates :description, length: { maximum: 150 }
    #validates :image, file_size: { less_than: 2.gigabytes }
    
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/add_infos_controller.rb
class AddInfosController < InheritedResources::Base

  private

    def add_info_params
      params.require(:add_info).permit(:name, :location, :number, :condition, :description, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mobs_controller.rb
class MobsController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts =Post.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/add_infos_helper.rb
module AddInfosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mobs_helper.rb
module MobsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/add_infos/_form.html.erb
<br><br><br>
<div class="container">
<%= form_for(@add_info) do |f| %>
  <% if @add_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@add_info.errors.count, "error") %> prohibited this add_info from being saved:</h2>

      <ul>
      <% @add_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :الاسم %><br>
    <%= f.text_field :name, required:true, class:"form-control"%>
  </div>
  <div class="field">
    <%= f.label :الموقع %><br>
    <%= f.text_field :location, required:true, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :الرقم %><br>
    <%= f.text_field :number, required:true, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :الحالة %><br>
    <%= f.text_field :condition, required:true, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :صورة_عن_الحالة %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :وصف_الحالة %><br>
    <%= f.text_area :description, required:true, class:"form-control", size: "60x12" %>
  </div>
  <div class="actions">
    <%= f.submit "تأكيد", class:"btn defaul"%>
  </div>
<% end %>
</div>

app/views/add_infos/edit.html.erb
<br><br><br><br><br><br>
<div class="container">
<h1>تعديل الحالة </h1>

<%= render 'form' %>

<%= link_to 'عرض', @add_info , class:"btn default"%> 
<%= link_to 'عودة', add_infos_path, class:"btn default" %>
</div><br><br><br>

app/views/add_infos/index.html.erb
<br><br><br><br><br><br>
<div class="container">
<p id="notice"><%= notice %></p>
<h1>عرض الحالات </h1>
<table>
  <tbody>
    <% @add_infos.each do |add_info| %>
      <div class="container">
        <div class="row">
          <div class="col-3">
       <%= add_info.name %>
          </div>
       <div class="col-3">
       <%= add_info.location %>
       </div>
       <div class="col-3">
       <%= add_info.description %>
       </div>
       <br>
       <div class="col-3">
        <%= link_to 'عرض', add_info , class:"btn default"%>
        <%= link_to 'مسح الحالة', add_info, method: :delete, data: { confirm:'هل انت متأكد؟' }, class:"btn default"%>
      </div>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'اضافة حالة جديدة', new_add_info_path, class:"btn default" %>
</div><br><br><br><br><br><br>

app/views/add_infos/new.html.erb
<br><br><br><br><br><br>
<div class="container">
<h1>اضافة حالة جديدة</h1>

<%= render 'form' %>

<%= link_to 'العودة', add_infos_path , class:"btn default" %>
</div>
<br><br><br><br><br><br>

app/views/add_infos/show.html.erb
<br><br><br><br><br><br>
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>الاسم:</strong>
  <%= @add_info.name %>
</p>
<br>
<p>
  <strong>الموقع:</strong>
  <%= @add_info.location %>
</p>
<br>
<p>
  <strong>رقم_الهاتف:</strong>
  <%= @add_info.number %>
</p>
<br>
<p>
  <strong>الحالة:</strong>
  <%= @add_info.condition %>
</p>
<br>
<p>
  <%= image_tag @add_info.image(:medium), class:"img-rounded"%>
</p>
<br>
<p>
  <strong>الوصف:</strong>
  <%= @add_info.description %>
</p>
<br>
<%= link_to 'تعديل', edit_add_info_path(@add_info), class:"btn default" %>
<%= link_to 'رجوع', add_infos_path , class:"btn default" %>
</div>
<br><br><br><br><br><br>

app/views/layouts/_footer.html.erb
<section id="action" class="action bg-primary roomy-40">
<div class="container">
<div class="row">
<div class="maine_action">
<div class="col-md-12">
<div class="action_item text-center">
<h2 class=" mn">تطوعك غير أجباري لكنه واجب أنساني نحو المجتمع!</h2>
</div></div></div></div></div></section>
<footer id="contact" class="footer action-lage bg-black p-top-80">
<!--<div class="action-lage"></div>-->
<div class="container">
<div class="row">
<div class="widget_area">
<div class="col-md-3">
<div class="widget_item widget_about">
<h5 class="text-white">تواصل معنا</h5>                       
<div class="widget_ab_item m-top-30">
<div class="item_icon">
<i class="fa fa-location-arrow"></i></div>
<div class="widget_ab_item_text">
<h6 class="text-white">الموقع</h6>
<p>
العراق-بغداد
</p></div></div>
<div class="widget_ab_item m-top-30">
<div class="item_icon"><i class="fa fa-phone"></i></div>
<div class="widget_ab_item_text">
<h6 class="text-white">هاتف </h6>
<p>+964 ### ### ####</p></div></div>
<div class="widget_ab_item m-top-30">
<div class="item_icon"><i class="fa fa-envelope-o"></i></div>
<div class="widget_ab_item_text">
<h6 class="text-white">البريد الالكتروني</h6>
<p>info@codeforiraq.org</p>
</div></div></div></div>
<div class="col-md-3">
<div class="widget_item widget_latest sm-m-top-50">
<h5 class="text-white">من نحن</h5>
<p class="m-top-20">نحن مجموعة من المبرمجين المتطوعين في المبادرة الانسانية البرمجة من أجل العراق. تهدف المبادرة الى خدمة وبناء المجتمع من الشعب والى الشعب عن طريق البرمجة.</p>
<div class="widget_latst_item m-top-30">
<div class="item_icon"><img src="../assets/uuu.png" alt="" /></div>
<div class="widget_latst_item_text"> 
<a href="http://codeforiraq.herokuapp.com/"><strong>
تفضلّ بزيارة الموقع الالكتروني لمبادرة البرمجة من اجل العراق
</strong></div></div></div></div>
<div class="col-md-6">
<div class="widget_item widget_newsletter sm-m-top-50">
<a href=""><h5 class="text-white">شعارنا</h5>
<div class="widget_brand m-top-40">
<img src="../assets/06.png" id="logo1" ></div>
<ul class="list-inline m-top-20">
<li>- <a href=""><i class="fa fa-facebook"></i></a></li>
<li><a href=""><i class="fa fa-twitter"></i></a></li>
<li><a href=""><i class="fa fa-linkedin"></i></a></li>
<li><a href=""><i class="fa fa-google-plus"></i></a></li>
<li><a href=""><i class="fa fa-dribbble"></i></a>  - </li>
</ul>
</div>
</div>
</div>
</div>
</div>
<div class="main_footer fix bg-mega text-center p-top-40 p-bottom-30 m-top-80">
<div class="col-md-12">
<p class="wow fadeInRight" data-wow-duration="1s">
 جميع الحقوق محفوظة © 2018 | All Rights Reserved © 2018
</p>
</div>
</div>
</footer>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default bootsnav navbar-fixed">
<div class="navbar-top bg-grey fix">
<div class="container">
<div class="row">
<div class="col-md-6">
<div class="navbar-callus text-left sm-text-center">
</div>
</div>
<div class="col-md-6">
<div class="navbar-socail text-right sm-text-center">
</div>
</div>
</div>
</div>
</div>
<!-- Start Top Search -->
<div class="top-search">
<div class="container">
<div class="input-group">
<span class="input-group-addon"><i class="fa fa-search"></i></span>
<input type="text" class="form-control" placeholder="أبحث">
<span class="input-group-addon close-search"><i class="fa fa-times"></i></span>
</div></div></div>
<!-- End Top Search -->
<div class="container"> 
<div class="attr-nav">
<ul>
<li class="search"><a href="#"><i class="fa fa-search"></i></a></li>
</ul>
</div> 
<!-- Start Header Navigation -->
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-menu">
<i class="fa fa-bars"></i>
</button>
<a class="navbar-brand" href="#">
<img src="../assets/06.png" id="logo">
</a>
</div>
<!-- End Header Navigation -->
<!-- navbar menu -->
<div class="collapse navbar-collapse" id="navbar-menu">
<ul class="nav navbar-nav navbar-right">
<li>
<%= link_to "حول المنصة", users_path %>
</li>
<li>
<%= link_to "حول التطبيق", mobs_path %>
</li>
<li>
<%= link_to "تبليغ عن الحالات الانسانية", new_add_info_path %>
</li>
<li>
	<%= link_to "الرئيسية", root_path %>
</li></ul>
</div></div> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/mobs/index.html.erb
<br><br><br>
<img src="../assets/01.jpg" id="pic">

<br>

app/views/posts/index.html.erb
<br><br><br>
<body data-spy="scroll" data-target=".navbar-collapse">
<!--Home Sections-->
<section class="home" class="home bg-black fix">
<div class="overlay">
<div class="container">
<div class="row">
<div class="main_home text-center">
<div class="col-md-12">
<br> <br><br><br><br><br><br>
<div class="hello_slid">
<div class="slid_item">
<div class="home_text ">
<h1 class="text-white"> يصبح الانسان عظيما تماما بالقدر الذي يعمل فيه من أجل رعاية أخيه الانسان 
<h3 class="text-white">- غاندي -</h3></div>
<center>
</div>
</div></center></div></div></div></div></div>
</section> 
<!--Featured Section-->
<section id="features" class="features">
<div class="container">
<div class="row">
<div class="main_features fix roomy-70">
<div class="col-md-4">
<div class="features_item sm-m-top-30">
<div class="f_item_icon">
<i class="fa fa-tablet"></i>
</div>
<div class="f_item_text">
<h3>حمّل تطبيق الجوال </h3>
<p>بأمكانكم ايضا تحميل تطبيق "أنا أنسان" على هواتفكم من المتجر الخاص بكم.</p></div></div></div>
<div class="col-md-4"><div class="features_item sm-m-top-30">
<div class="f_item_icon"><i class="fa fa-bullhorn"></i></div>
<div class="f_item_text">
<h3>أذا أحسست بألالم فأنت "حي" وأذا أحسست بألام ألأخرين فأنت "أنسان"</h3>
<p>بأمكان أي فرد التبليغ عن حالة أنسانية, ونحن سنعلن عنها في الموقع الالكتروني.</p>
</div></div></div>
<div class="col-md-4">
<div class="features_item sm-m-top-30">
<div class="f_item_icon">
<i class="fa fa-handshake-o"></i>
</div>
<div class="f_item_text">
<h3>العطاء .. بذرة من نقاء تثمر خيرا وصفاء</h3>
<p>نحن نؤمن بأن كل فرد قادر على تقديم الخدمات التي يحتاجها المجتمع, فمن اعطى وقت الحاجة كانت عطيته مضاعفة, قال تعالى :"فمن يعمل مثقال ذرة خيرا يره"</p>
</div></div></div></div></div></div></div>
</section>
<br><br>
<div class="container">
     <hr>
    <!--div class="row">
        <div class="col-md-3 col-md-offset-3">
    <h3>حمل التطبيق الان </h3>
        </div>
    </div-->
</div>
<p id="notice">
<%= notice %>
</p>
<br><br>

app/views/users/index.html.erb
<br><br><br><br><br>
<!--About Us Section-->
<div class="container">
<div class="row my-4">
<div class="col-md-6">
<img class="img-fluid rounded" src="assets/تطوع.jpg" alt=""></div>
<!-- /.col-lg-8 -->
<div class="col-md-6">
<h1 class="head-style">حوّل المِنصة</h1>
<p class="p1">الإنسان بطبعِهِ لا يستطيعُ العيش بمفردِهِ؛ بل يحتاجُ إلى أنْ يكونَ ضمن مُجتمعٍ، ومع مجموعةٍ من الأشخاص سواءً في منزلهِ، أو مكان دراستِهِ، أو عملهِ؛ لأنّ الخصائص الاجتماعيّة هي مِن سِمات الطّبيعة الإنسانيّة، فالفطرةُ السّليمة تدعوُ الإنسان دائماً إلى تقديمِ الخير وتنحية الشرّ بشكلٍ نهائيّ. لذا انطلاقا من هذا المبدأ كان من الضروري أيجاد جسم يجمع بين المحتاجين والمتطوعين. هذا الجسم يعرف باسم "منصة أنا أنسان". وهو موقع الكتروني الأول من نوعه في العراق والذي يهدف الى عرض الحالات الأنسانية في الصفحة الرئيسية إذ يتمكن من خلاله الأفراد الذين يتمتعون بالمهارة والحماس, تقديمُ المساعدةِ والعون والجهد مِن أجل العمل على تحقيقِ الخير في المُجتمعِ عُموماً ولأفراده خصوصاً.</p>
<br>
<h1 class="head-style">رسالتنا</h1>
<p class="p1">ندعوُ الإنسان دائماً إلى تقديمِ الخير وتنحية الشرّ بشكلٍ نهائيّ, وأن مِن سِمات الطّبيعة الإنسانيّة، الخصائص الاجتماعيّة لأنّ الإنسان بطبعِهِ لا يستطيعُ العيش بمفردِهِ؛ بل يحتاجُ إلى أنْ يكونَ ضمن مُجتمعٍ،, ومع مجموعةٍ من الأشخاص سواءً في منزلهِ، أو مكان دراستِهِ، أو عملهِ.</p><br/><br/>
</div></div></div>           
<section id="test" class="test bg-grey roomy-60 fix">
<div class="container">
<div class="row">                        
<div class="main_test fix">
<div class="col-md-12 col-sm-12 col-xs-12">
<div class="head_title text-center fix">
<p class="text-bg"><strong>حول المبرمجين</strong> </p>
<p class="p2">نحن مجموعة من المبرمجين المتطوعين في المبادرة الانسانية البرمجة من أجل العراق. تهدف المبادرة الى خدمة وبناء المجتمع من الشعب والى الشعب عن طريق البرمجة</h5></div></div>
<div class="col-md-6">
<div class="test_item fix">
<div class="item_img">
<img class="img-circle" src="assets/FB_IMG_1516295182348.jpg" alt="" />
<i class="fa fa-quote-left"></i></div>
<div class="item_text">
<p class="p21">محمد عيسى</p>
<h6>muhammed.essa@codeforiraq.org</h6>
<p class="p22">"صاحب ومؤسس مبادرة البرمجة من أجل العراق"
</p><br></div></div></div>
<div class="col-md-6">
<div class="test_item fix sm-m-top-30">
<div class="item_img">
<img class="img-circle" src="assets/Doozy+Labs+Responsive+Website+Development+Icon.png" alt="" /><i class="fa fa-quote-left"></i></div>
<div class="item_text">
<p class="p21">المبرمجين</p>
<h6>info@codeforiraq.org</h6>
<p>front-end | Zena Hasan<br> Back-end | Fatima Amer<br> Mobile Application | Rana Abdullah.</p>
</div></div></div></div></div></div>
</section>